setwd("E:/RScript/R_in_Action")
library(VIM)
library(mice)
data("sleep",package = "VIM")
str(sleep)
prop.table(table(is.na(sleep$Dream),useNA = "ifany"))
summary(sleep)
aggr(sleep,prop=F,numbers=T)
marginplot(sleep[c("Gest","Dream")],pch = c(16),col = c("darkgray","red","blue"))
